/* Define Action Types for Expenses */
export const NEW_EXPENSE_ENTRY = 'NEW_EXPENSE_ENTRY';
export const EXPENSE_LIST = 'EXPENSE_LIST';
export const EXPENSE_LIST_PENDING = 'EXPENSE_LIST_PENDING';
export const EXPENSE_LIST_FULFILLED = 'EXPENSE_LIST_FULFILLED';
export const EXPENSE_LIST_REJECTED = 'EXPENSE_LIST_REJECTED';
export const UPDATE_EXPENSE_ENTRY = 'UPDATE_EXPENSE_ENTRY';
export const DELETE_EXPENSE_ENTRY = 'DELETE_EXPENSE_ENTRY';
export const EXPENSE_LIST_BY_ID = 'EXPENSE_LIST_BY_ID';

/* Define Action Types for Category */
export const NEW_CATEGORY_ENTRY = 'NEW_CATEGORY_ENTRY';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_LIST_PENDING = 'CATEGORY_LIST_PENDING';
export const CATEGORY_LIST_FULFILLED = 'CATEGORY_LIST_FULFILLED';
export const CATEGORY_LIST_REJECTED = 'CATEGORY_LIST_REJECTED';
export const UPDATE_CATEGORY_ENTRY = 'UPDATE_CATEGORY_ENTRY';
export const DELETE_CATEGORY_ENTRY = 'DELETE_CATEGORY_ENTRY';
export const CATEGORY_LIST_BY_ID = 'CATEGORY_LIST_BY_ID';
